Algoritmo "Aula_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/12/2021
Var
// Seção de Declarações das variáveis 
msgs: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
msg <- "Olá Mundo"
Escreval(msg)
Fimalgoritmo